### ISSUE TITLE
Theme setting influences viewport lighting influence

### ISSUE THREAD

**Issue by eldeesmith** [paulcoops/blender_pro-theme#1]
I don't think it's an issue with your theme, but likely a bug with Blender- I just wanted to make you aware of the issue in case you were not already. I've posted a bug here:

https://developer.blender.org/T68379

**Comment by paulcoops** [comment]
Thanks for reporting this. Unfortunately, I'm unable to reproduce this issue on my dusty old mac. When I open the default cube, change the viewport shading to MatCap and switch between the Blender Dark, Light and Pro themes I don't get any difference in shading. Can you maybe share the .blend file so I can see if I can reproduce this issue?

**Comment by eldeesmith** [comment]
After testing it on a couple other machines I believe it may be caused by Spyder's auto-monitor calibration. I think the theme itself affects the display's histogram enough that Spyder tries to automatically adjust the whitepoint to balance it. I will test it without the calibration software running tomorrow when I'm back at work and verify

**Comment by paulcoops** [comment]
Hi, were you able to test it? I'm very curious about your findings.
